// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ModificaEmailTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void modificaEmailOK() {
    driver.get("http://localhost:8080/shodan_maven/");
    driver.manage().window().setSize(new Dimension(1900, 1020));
    driver.findElement(By.id("login-username")).click();
    driver.findElement(By.id("login-username")).sendKeys("slave");
    driver.findElement(By.id("login-password")).sendKeys("123");
    driver.findElement(By.id("login-password")).sendKeys(Keys.ENTER);
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.id("settings-link")));
    }
    driver.findElement(By.id("settings-link")).click();
    driver.findElement(By.id("settings-input-last-email")).click();
    driver.findElement(By.id("settings-input-last-email")).sendKeys("slave@shodan.it");
    driver.findElement(By.id("settings-input-email")).sendKeys("slave2@shodan.it");
    driver.findElement(By.id("settings-submit-email")).click();
    assertThat(driver.findElement(By.id("email-change-message")).getText(), is("Email modificata con successo!"));
  }
  @Test
  public void modificaEmailNuovaEmailMancante() {
    driver.get("http://localhost:8080/shodan_maven/");
    driver.manage().window().setSize(new Dimension(1900, 1020));
    driver.findElement(By.id("login-username")).click();
    driver.findElement(By.id("login-username")).sendKeys("dummy");
    driver.findElement(By.id("login-password")).sendKeys("123");
    driver.findElement(By.id("login-submit")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.id("settings-link")));
    }
    driver.findElement(By.id("settings-link")).click();
    driver.findElement(By.id("settings-input-last-email")).click();
    driver.findElement(By.id("settings-input-last-email")).sendKeys("slave@shodan.it");
    driver.findElement(By.id("settings-input-last-email")).click();
    driver.findElement(By.id("settings-input-last-email")).sendKeys("dummy@shodan.it");
    driver.findElement(By.id("settings-submit-email")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[contains(@email-change-message,\'\')]"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void modificaEmailFormatoNonValido() {
    driver.get("http://localhost:8080/shodan_maven/");
    driver.manage().window().setSize(new Dimension(1900, 1020));
    driver.findElement(By.id("login-username")).click();
    driver.findElement(By.id("login-username")).sendKeys("dummy");
    driver.findElement(By.id("login-password")).sendKeys("123");
    driver.findElement(By.id("login-password")).sendKeys(Keys.ENTER);
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.id("settings-link")));
    }
    driver.findElement(By.id("settings-link")).click();
    driver.findElement(By.id("settings-input-last-email")).click();
    driver.findElement(By.id("settings-input-last-email")).sendKeys("dummy@shodan.it");
    driver.findElement(By.id("settings-input-email")).sendKeys("dd@@dd.it");
    driver.findElement(By.id("settings-submit-email")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[contains(@password-change-message,\'\')]"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void modificaEmailEmailInUso() {
    driver.get("http://localhost:8080/shodan_maven/");
    driver.manage().window().setSize(new Dimension(1900, 1020));
    driver.findElement(By.id("login-username")).click();
    driver.findElement(By.id("login-username")).sendKeys("dummy");
    driver.findElement(By.id("login-password")).sendKeys("123");
    driver.findElement(By.id("login-password")).sendKeys(Keys.ENTER);
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.id("settings-link")));
    }
    driver.findElement(By.id("settings-link")).click();
    driver.findElement(By.id("settings-input-last-email")).click();
    driver.findElement(By.id("settings-input-last-email")).sendKeys("dummy@shodan.it");
    driver.findElement(By.id("settings-input-email")).sendKeys("antonio@shodan.it");
    driver.findElement(By.id("settings-submit-email")).click();
    assertThat(driver.findElement(By.id("email-change-message")).getText(), is("Impossibile usare questa email."));
  }
  @Test
  public void modificaEmailEmailAttualeErrata() {
    driver.get("http://localhost:8080/shodan_maven/");
    driver.manage().window().setSize(new Dimension(1900, 1020));
    driver.findElement(By.id("login-username")).click();
    driver.findElement(By.id("login-username")).sendKeys("dummy");
    driver.findElement(By.id("login-password")).click();
    driver.findElement(By.id("login-password")).sendKeys("123");
    driver.findElement(By.id("login-submit")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.id("settings-link")));
    }
    driver.findElement(By.id("settings-link")).click();
    driver.findElement(By.id("settings-input-last-email")).click();
    driver.findElement(By.id("settings-input-last-email")).sendKeys("duummy@shodan.it");
    driver.findElement(By.id("settings-input-email")).sendKeys("nuova@shodan.it");
    driver.findElement(By.id("settings-input-email")).sendKeys(Keys.ENTER);
    assertThat(driver.findElement(By.id("email-change-message")).getText(), is("Non hai inserito correttamente la tua email attuale."));
  }
}
