// Generated by Selenium IDE

package seleniumtesting;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RicaricaSaldoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "../commons/driver/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void ricaricaSaldoQuantitaNonValida() {
    driver.get("http://localhost:8080/shodan_maven/");
    driver.manage().window().setSize(new Dimension(1898, 1018));
    driver.findElement(By.id("login-username")).click();
    driver.findElement(By.id("login-username")).sendKeys("slave");
    driver.findElement(By.id("login-password")).sendKeys("123");
    driver.findElement(By.id("login-password")).sendKeys(Keys.ENTER);
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.id("settings-link")));
    }
    driver.findElement(By.id("settings-link")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.id("add-card")));
    }
    driver.findElement(By.id("add-card")).click();
    driver.findElement(By.id("amount-input")).click();
    driver.findElement(By.id("amount-input")).sendKeys("0");
    driver.findElement(By.cssSelector(".valid-credit-card")).click();
    assertThat(driver.findElement(By.id("cards-message")).getText(), is("Quantita\\\' non valido."));
  }
  @Test
  public void ricaricaSaldoOK() {
    driver.get("http://localhost:8080/shodan_maven/");
    driver.manage().window().setSize(new Dimension(1898, 1018));
    driver.findElement(By.id("login-username")).sendKeys("admin");
    driver.findElement(By.id("login-password")).sendKeys("123");
    driver.findElement(By.id("login-submit")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.id("roles-link")));
    }
    driver.findElement(By.id("roles-link")).click();
    driver.findElement(By.cssSelector(".role-item:nth-child(2)")).click();
    driver.findElement(By.id("settings-link")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.id("add-card")));
    }
    driver.findElement(By.id("add-card")).click();
    driver.findElement(By.cssSelector(".VISA h1")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.id("cards-message")));
    }
    assertThat(driver.findElement(By.id("cards-message")).getText(), is("Ricarica effettuata con successo!"));
  }
  @Test
  public void ricaricaSaldoFormatoQuantitaNonValido() {
    driver.get("http://localhost:8080/shodan_maven/");
    driver.manage().window().setSize(new Dimension(1898, 1018));
    driver.findElement(By.id("login-username")).click();
    driver.findElement(By.id("login-username")).sendKeys("slave");
    driver.findElement(By.id("login-password")).sendKeys("123");
    driver.findElement(By.id("login-password")).sendKeys(Keys.ENTER);
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.id("settings-link")));
    }
    driver.findElement(By.id("settings-link")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.id("add-card")));
    }
    driver.findElement(By.id("add-card")).click();
    driver.findElement(By.id("amount-input")).click();
    driver.findElement(By.id("amount-input")).sendKeys("uno");
    driver.findElement(By.cssSelector(".valid-credit-card")).click();
    assertThat(driver.findElement(By.id("cards-message")).getText(), is("Formato quantita\\\' non valido"));
  }
  @Test
  public void ricaricaSaldoCartaScaduta() {
    driver.get("http://localhost:8080/shodan_maven/");
    driver.manage().window().setSize(new Dimension(1898, 1018));
    driver.findElement(By.id("login-username")).sendKeys("slave");
    driver.findElement(By.id("login-password")).sendKeys("123");
    driver.findElement(By.id("login-password")).sendKeys(Keys.ENTER);
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.id("settings-link")));
    }
    driver.findElement(By.id("settings-link")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.id("add-card")));
    }
    driver.findElement(By.id("add-card")).click();
    driver.findElement(By.cssSelector(".MASTERCARD h1")).click();
    assertThat(driver.findElement(By.id("cards-message")).getText(), is("Carta scaduta"));
  }
}
